INSERT INTO Flight (FLIGHT_ID,FLIGHT_DATETIME,FLIGHT_ORIGIN,FLIGHT_DESTINATION) VALUES (1,null,'Bogota','Miami');
INSERT INTO Flight (FLIGHT_ID,FLIGHT_DATETIME,FLIGHT_ORIGIN,FLIGHT_DESTINATION) VALUES (2,null,'Medellin','Choco');
INSERT INTO Flight (FLIGHT_ID,FLIGHT_DATETIME,FLIGHT_ORIGIN,FLIGHT_DESTINATION) VALUES (3,null,'Rionegro','San Andres');
INSERT INTO Flight (FLIGHT_ID,FLIGHT_DATETIME,FLIGHT_ORIGIN,FLIGHT_DESTINATION) VALUES (4,null,'Bogota','Rio de Janeiro');